model_sets=[[keras.layers.Flatten(input_shape=(28, 28)),
             keras.layers.Dense(units=128, activation='relu'),
             keras.layers.Dense(units=10, activation='softmax')],
            [keras.layers.Conv2D(30, kernel_size=(3, 3),strides=2,activation='relu',input_shape=(28, 28, 1)),
             keras.layers.Dropout(0.5),
             keras.layers.Conv2D(30, kernel_size=(3, 3), strides=2, activation='relu'),
             keras.layers.Dropout(0.5),
             keras.layers.Flatten(),
             keras.layers.Dense(units=128, activation='relu'),
             keras.layers.Dense(units=10, activation='softmax')],
            [keras.layers.Conv2D(32,(5, 5),input_shape=(28, 28, 1),activation="relu",),
             keras.layers.Conv2D(32, (5, 5), activation="relu"),
             keras.layers.MaxPooling2D(pool_size=(2, 2)),
             keras.layers.Conv2D(64, (5, 5), activation="relu"),
             keras.layers.Conv2D(64, (5, 5), activation="relu"),
             keras.layers.MaxPooling2D(pool_size=(2, 2)),
             keras.layers.Dropout(0.5),
             keras.layers.Flatten(),
             keras.layers.Dense(units=128, activation='relu'),
             keras.layers.Dense(units=10, activation='softmax')]
            ]
